services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: AuctionDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mogodb
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 }).ok' | mongosh mongodb://root:mongopw@mongodb:27017/?authSource=admin --quiet"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
  auction-svc:
    image: slimedemon/auction-svc
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
  search-svc:
    image: slimedemon/search-svc
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
  identity-svc:
    image: slimedemon/identity-svc
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
  gateway-svc:
    image: slimedemon/gateway-svc
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
  bid-svc:
    image: slimedemon/bid-svc
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
  notify-svc:
    image: slimedemon/notify-svc
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
  web-app:
    image: slimedemon/web-app
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
volumes:
  pgdata:
  mongodata: