import type { Metadata, Viewport } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ToasterProvider from "./providers/ToasterProvider";
import SignalRProvider from "./providers/SignalRProvider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Auto Bid App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ToasterProvider />
          <NavBar />
          <main className="container mx-auto px-4 sm:px-6 lg:px-8 pt-6 md:pt-10">
            <SignalRProvider>
              {children}
            </SignalRProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
